-- ⚠️ ARQUIVO OBSOLETO — NÃO RODE ESTE SQL.
--
-- A definição válida de `carregar_contexto` vive em `migracao-robustez.sql`.
--
-- Este arquivo criou a primeira versão da função (que devolvia apenas
-- historico/prompts/produtos). A versão atual devolve também o objeto `lead`, e
-- é dele que dependem duas proteções:
--
--   * modo sem venda quando `status = 'aguardando_humano'` — sem ele, o agente
--     volta a vender para quem foi escalado por sofrimento;
--   * exclusão do que a lead já comprou do catálogo ofertável.
--
-- Rodar este arquivo DEPOIS da migração rebaixaria a função para a versão
-- antiga **sem erro nenhum** (`create or replace` sobrescreve em silêncio). O
-- agente continuaria respondendo, só que sem as duas proteções — falha
-- silenciosa, do tipo que só aparece num caso real.
--
-- Por isso o conteúdo foi removido em vez de mantido "para referência":
-- um SQL executável parado numa pasta é um SQL que alguém executa.
--
-- Ordem correta das migrações:
--   1. schema.sql
--   2. migracao-aguardando-humano.sql
--   3. migracao-entrega.sql
--   4. migracao-robustez.sql        <- define carregar_contexto
--   5. seed-prompt-objecoes.sql
--
-- Ver `../APLICAR-AO-VIVO.md`.
